// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdmkUWnyNcv9Rvy39jmAxW7kborrzAvMU',
    appId: '1:1041311397920:web:9c09220a78bbbe37646445',
    messagingSenderId: '1041311397920',
    projectId: 'vbwf-4bc0c',
    authDomain: 'vbwf-4bc0c.firebaseapp.com',
    storageBucket: 'vbwf-4bc0c.firebasestorage.app',
    measurementId: 'G-3T0VHZYW81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPw61wH2QyT7G1F8Lwq0VW7gTfEGXz0yk',
    appId: '1:1041311397920:android:b7ee91d3142b02ad646445',
    messagingSenderId: '1041311397920',
    projectId: 'vbwf-4bc0c',
    storageBucket: 'vbwf-4bc0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgEuC6vcX2U31bIQ9snGOT1HHpTeNcko',
    appId: '1:1041311397920:ios:83bfe1bda2f1e7f3646445',
    messagingSenderId: '1041311397920',
    projectId: 'vbwf-4bc0c',
    storageBucket: 'vbwf-4bc0c.firebasestorage.app',
    iosBundleId: 'com.thehinhvn.thehinhvn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgEuC6vcX2U31bIQ9snGOT1HHpTeNcko',
    appId: '1:1041311397920:ios:83bfe1bda2f1e7f3646445',
    messagingSenderId: '1041311397920',
    projectId: 'vbwf-4bc0c',
    storageBucket: 'vbwf-4bc0c.firebasestorage.app',
    iosBundleId: 'com.thehinhvn.thehinhvn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdmkUWnyNcv9Rvy39jmAxW7kborrzAvMU',
    appId: '1:1041311397920:web:2ea9abaa174e3aee646445',
    messagingSenderId: '1041311397920',
    projectId: 'vbwf-4bc0c',
    authDomain: 'vbwf-4bc0c.firebaseapp.com',
    storageBucket: 'vbwf-4bc0c.firebasestorage.app',
    measurementId: 'G-R269SJ00WB',
  );
}
